import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_clean_architecture/features/booking/domain/entities/booking_entity.dart';
import 'package:flutter_clean_architecture/features/booking/domain/usecases/create_booking_usecase.dart';
import 'package:flutter_clean_architecture/features/booking/domain/usecases/process_payment_usecase.dart';
import 'package:flutter_clean_architecture/features/booking/presentation/cubit/booking_state.dart';

class BookingCubit extends Cubit<BookingState> {
  final CreateBookingUseCase createBookingUseCase;
  final ProcessPaymentUseCase processPaymentUseCase;

  BookingCubit({
    required this.createBookingUseCase,
    required this.processPaymentUseCase,
  }) : super(BookingInitial());

  void reset() {
    emit(BookingInitial());
  }

  Future<void> submitBookingRequest({
    required int guideId,
    required String touristName,
    required DateTime date,
    required int guests,
    required double totalPrice,
    String? message,
  }) async {
    emit(BookingLoading());
    try {
      final booking = BookingEntity(
        id: '', // Generated by remote datasource
        guideId: guideId,
        touristName: touristName,
        date: date,
        guests: guests,
        totalPrice: totalPrice,
        status: 'pending',
        message: message,
      );
      final result = await createBookingUseCase(booking);
      emit(BookingCreated(result));
    } catch (e) {
      emit(BookingError(e.toString()));
    }
  }

  Future<void> processPayment({
    required String bookingId,
    required double amount,
  }) async {
    emit(PaymentProcessing());
    try {
      final success = await processPaymentUseCase(bookingId, amount);
      if (success) {
        emit(PaymentSuccess('TXN-${DateTime.now().millisecondsSinceEpoch}'));
      } else {
        emit(const BookingError('Payment declined. Please try another card.'));
      }
    } catch (e) {
      emit(BookingError(e.toString()));
    }
  }
}
